name: cheese_me_up
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  path_provider: ^0.4.1
  firebase_auth: ^0.5.18
  firebase_core: ^0.2.4
  firebase_database: ^1.0.2
  google_sign_in: ^3.0.5
  flutter_launcher_icons: ^0.6.1
  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_icons:
  image_path: "assets/media/icons/cheese_jpg.jpg"
  android: true 
  ios: true 
  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/media/img/cheese/abbaye-de-belloc.jpg
   - assets/media/img/cheese/Boulette_dAvesnes.jpg
   - assets/media/img/cheese/cantal.jpg
   - assets/media/img/cheese/Belval-biere.jpg
   - assets/media/img/cheese/Boulette_dAvesnes.jpg
   - assets/media/img/cheese/Fromage_citeaux.jpg
   - assets/media/img/cheese/cantal.jpg
   - assets/media/img/cheese/Abbots-Gold.jpg
   - assets/media/img/cheese/Gran-Reserva-2.jpg
   - assets/media/img/cheese/Gruy-laib-keil_klein.jpg
   - assets/media/img/cheese/Appenzeller.jpg
   - assets/media/img/cheese/Danish_Blue.jpg
   - assets/media/img/cheese/abbaye-de-belloc.jpg
   - assets/media/img/cheese/1_3.JPG
   - assets/media/img/cheese/Abondance1.jpg
   - assets/media/img/cheese/Laiib-Offen-Klein.jpg
   - assets/media/img/cheese/1_12.JPG
   - assets/media/img/cheese/Acapella_Cheese...jpg
   - assets/media/img/cheese/emmental.jpg
   - assets/media/img/cheese/Kaltbach_Emmentaler_AOP.jpg
   - assets/media/img/cheese/Kaltbach_Le_Gruyere_AOP.jpg
   - assets/media/img/cheese/Gruyere1.jpg
   - assets/media/img/cheese/holzofer.jpg
   - assets/media/img/cheese/Tilsit_cheese_1.jpg
   - assets/media/img/cheese/SbrinzAOC.jpg
   - assets/media/img/cheese/reggi2113.jpg
   - assets/media/img/cheese/tete-de-moine.jpg
   - assets/media/img/cheese/Vacherin_Fribourgeois.png
   - assets/media/img/cheese/Tomme.jpg
   - assets/media/img/cheese/vacherin_france.jpg
   - assets/media/img/cheese/691px-Washed-rind_cheese.jpg
   # cheese icons:
   - assets/media/icons/cheese_color.png
   - assets/media/icons/cheese_bw.png
   - assets/media/icons/cheese_wb.png
   - assets/media/icons/trophy.png
   - assets/media/icons/history.png
   - assets/media/icons/settings.png
   - assets/media/icons/facebook.png
   - assets/media/icons/google.png
   # wallpapers
   - assets/media/img/wallpapers/wp_cheese_001.jpg
   - assets/media/img/wallpapers/wp_cows_001.png
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
